version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday

    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday