name: Somtoday2MicrosoftSDS CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validation:
    name: Validate
    uses: ./.github/workflows/validate.yml
    with:
      run_container_smoke: true
